---
repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.21.1
    hooks:
      - id: ansible-lint
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.37.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/ansible-community/antsibull-changelog.git
    rev: 0.23.0
    hooks:
      - id: antsibull-changelog-lint
      - id: antsibull-changelog-lint-changelog-yaml
