---
namespace: lab
name: azure_infrastructure_config_demos
version: 2.0.0
readme: README.md
authors:
  - Scott Harwell <sharwell@redhat.com>
description: Azure use cases in the Ansible Cloud Content Incubation program.
license_file: "LICENSE"
tags:
  - "cloud"
  - "azure"
dependencies:
  azure.azcollection: ">=1.16.0"
  ansible.windows: ">=2.0.0"
  community.general: ">=7.1.0"
repository: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
documentation: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
homepage: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
issues: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git/issues
build_ignore:
  - ".tox"
  - ".git"
  - ".github"
  - ".gitignore"
