---
- name: Prepare the local VM for migration to Azure
  hosts: vm
  gather_facts: true
  become: true
  tasks:
    - name: Prepare the VM with OS requirements to run in Azure
      ansible.builtin.import_role:
        name: vm_to_azure_prep
  tags:
    - vm_prep
    - proxmox

- name: Check local file system to see if converted image already exists
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Check if the converted image file already exists locally
      ansible.builtin.import_role:
        name: proxmox_vm_conversion
        tasks_from: local_vm_image_check
  tags:
    - proxmox

- name: Convert Proxmox VM to Azure format and move locally in preparation for migration to Azure
  hosts: proxmox
  gather_facts: false
  become: false
  tasks:
    - name: Convert Proxmox VM image and move to localhost
      when: not hostvars['localhost'].proxmox_vm_migration_local_image_exists.stat.exists or
            proxmox_vm_migration_run_if_local_image_exists
      ansible.builtin.import_role:
        name: proxmox_vm_conversion
  tags:
    - proxmox

- name: Upload VM image to Azure and deploy it as a new VM
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    vm_to_azure_file_name: "{{ hostvars['localhost'].proxmox_vm_migration_image_filename }}"
  tasks:
    - name: Run migrate local vm role
      ansible.builtin.import_role:
        name: vm_to_azure
  tags:
    - azure
