---
- name: Migrate Proxmox VM to Azure VM
  hosts: proxmox
  gather_facts: false
  become: false
  tasks:
    - name: Run local cleanup task
      ansible.builtin.import_role:
        name: proxmox_vm_migration
