---
- name: Verify required parameters prior to running automation
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - proxmox_vm_migration_source_format is defined
          - proxmox_vm_migration_image_src is defined
          - proxmox_vm_migration_image_dest is defined
          - proxmox_vm_migration_image_filename is defined
          - proxmox_vm_id is defined
          - proxmox_api_user is defined
          - proxmox_api_token is defined
          - proxmox_api_secret is defined
          - proxmox_api_host is defined
        fail_msg: "Required variables not set"

- name: Prep Proxmox for VM image clone
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Shutdown VM
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: stop_proxmox_vm

- name: Create VM image
  hosts: proxmox
  gather_facts: false
  become: true
  tasks:
    - name: Create Azure compatible VM image
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: convert_image

- name: Start VM
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Start VM
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: start_proxmox_vm

# Since the Proxmox host will not have the Azure CLI or modules, move the file to the automation host for upload to Azure.
- name: Move VM image
  hosts: proxmox
  gather_facts: false
  become: false
  tasks:
    - name: Move VM image to automation host
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: move_azure_image

- name: Cleanup Proxmox
  hosts: proxmox
  gather_facts: false
  become: true
  tasks:
    - name: Run Proxmox cleanup task
      when: proxmox_vm_migration_delete_copied_images_after_migration
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: cleanup_proxmox

- name: Cleanup local
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Run local cleanup task
      when: proxmox_vm_migration_delete_copied_images_after_migration
      ansible.builtin.import_role:
        name: proxmox_vm_migration
        tasks_from: cleanup_local
