---
- name: Convert disk image to Azure compatible format
  ansible.builtin.command:
    cmd: "qemu-img convert -f {{ proxmox_vm_migration_source_format }} -O vpc {{ proxmox_vm_migration_image_src }} {{ proxmox_vm_migration_image_dest }}"
  register: proxmox_vm_migration_conversion
  changed_when: proxmox_vm_migration_conversion.rc == 0
  failed_when: proxmox_vm_migration_conversion.rc != 0
