---
- name: Start the VM
  when: proxmox_vm_migration_start_proxmox_vm
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token }}"
    api_token_secret: "{{ proxmox_api_secret }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ proxmox_vm_id }}"
    state: started
    timeout: 60
