---
- name: Stop the VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token }}"
    api_token_secret: "{{ proxmox_api_secret }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ proxmox_vm_id }}"
    state: stopped
