---
vm_size: Standard_DS3_v2
disk_type: Standard_LRS
create_vm_priority: None
create_vm_max_price: -1
create_vm_security_group_rules:
  - name: SSH
    protocol: Tcp
    destination_port_range: 22
    access: Allow
    priority: 1001
    direction: Inbound
