---
- name: Prepare RHEL VM for migration to Azure
  when:
    - ansible_facts["os_family"] == "RedHat"
    - ansible_distribution_major_version | int >= 8
  ansible.builtin.import_tasks:
    file: rhel.yml
