---
- name: Disable extensions on Arc connected devices
  ansible.builtin.command: |
    az connectedmachine extension delete \
    --machine-name "{{ item }}" \
    --name "{{ arc_name }}" \
    --resource-group "{{ arc_resource_group }}" \
    --no-wait \
    --yes
  loop: "{{ arc_hosts }}"
  register: arc_results
  changed_when: arc_results.rc != 0

- name: Register Stats
  ansible.builtin.set_stats:
    data:
      arc_enablement_results: arc_results
