---
- name: Check if the Connected Machine Agent has already been downloaded on Linux servers
  ansible.builtin.stat:
    path: /usr/bin/azcmagent
    get_attributes: false
    get_checksum: false
  register: arc_azcmagent_lnx_downloaded
  when: ansible_system == 'Linux'

- name: Download the Connected Machine Agent on Linux servers
  become: true
  ansible.builtin.get_url:
    url: https://aka.ms/azcmagent
    dest: /tmp/install_linux_azcmagent.sh
    mode: "700"
  when:
    - (ansible_system == 'Linux')
    - (not arc_azcmagent_lnx_downloaded.stat.exists)

- name: Install the Connected Machine Agent on Linux servers
  become: true
  ansible.builtin.command: bash /tmp/install_linux_azcmagent.sh
  register: arc_azcmagent_lnx_install
  when:
    - (ansible_system == 'Linux')
    - (not arc_azcmagent_lnx_downloaded.stat.exists)
  failed_when: (arc_azcmagent_lnx_install.rc not in [0, 16])
  changed_when: (arc_azcmagent_lnx_install.rc in [0, 16])

- name: Check if the Connected Machine Agent has already been downloaded on Windows servers
  ansible.windows.win_stat:
    path: C:\Program Files\AzureConnectedMachineAgent
  register: arc_azcmagent_win_downloaded
  when: ansible_os_family == 'Windows'

- name: Download the Connected Machine Agent on Windows servers
  ansible.windows.win_get_url:
    url: https://aka.ms/AzureConnectedMachineAgent
    dest: C:\Users\AppData\Local\Temp\AzureConnectedMachineAgent.msi
  when: (ansible_os_family == 'Windows') and (not arc_azcmagent_win_downloaded.stat.exists)

- name: Install the Connected Machine Agent on Windows servers
  ansible.windows.win_package:
    path: C:\Users\AppData\Local\Temp\AzureConnectedMachineAgent.msi
  when: (ansible_os_family == 'Windows') and (not arc_azcmagent_win_downloaded.stat.exists)

- name: Check if the Connected Machine Agent has already been connected
  become: true
  ansible.builtin.command: azcmagent check
  register: arc_azcmagent_lnx_connected
  ignore_errors: true
  when: ansible_system == 'Linux'
  failed_when: (arc_azcmagent_lnx_connected.rc not in [0, 16])
  changed_when: false

- name: Check if the Connected Machine Agent has already been connected on Windows
  ansible.windows.win_command: azcmagent check
  register: arc_azcmagent_win_connected
  when: ansible_os_family == 'Windows'
  ignore_errors: true
  failed_when: (arc_azcmagent_win_connected.rc not in [0, 16])
  changed_when: false

- name: Connect the Connected Machine Agent on Linux servers to Azure Arc
  become: true
  ansible.builtin.command: |
    azcmagent connect \
    --service-principal-id "{{ service_principal_id }}" \
    --service-principal-secret "{{ service_principal_secret }}" \
    --resource-group "{{ resource_group }}" \
    --tenant-id "{{ tenant_id }}" \
    --location "{{ region }}" \
    --subscription-id "{{ subscription_id }}"
  register: arc_azcmagent_lnx_connect
  when:
    - (ansible_system == 'Linux')
    - (arc_azcmagent_lnx_connected.rc is defined and arc_azcmagent_lnx_connected.rc != 0)
  failed_when: (arc_azcmagent_lnx_connect.rc not in [0, 16])
  changed_when: (arc_azcmagent_lnx_connect.rc in [0, 16])

- name: Connect the Connected Machine Agent on Windows servers to Azure
  ansible.windows.win_shell: '& $env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe connect --service-principal-id "{{ service_principal_id }}" --service-principal-secret "{{ service_principal_secret }}" --resource-group "{{ resource_group }}" --tenant-id "{{ tenant_id }}" --location "{{ region }}" --subscription-id "{{ subscription_id }}"'
  when:
    - (ansible_os_family == 'Windows')
    - (arc_azcmagent_win_connected.rc is defined and arc_azcmagent_win_connected.rc != 0)
