---
- name: Create Network Security Group that allows VM ports
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ network_sec_group_name }}"
    rules: "{{ create_vm_security_group_rules }}"
    tags:
      ansible-collection: azure.infrastructure_config_demos
      ansible-role: vms
      ansible-task: create_rhel_vm

- name: Create virtual network interface card with internal ip
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ subnet_name }}"
    security_group: "{{ network_sec_group_name }}"
    tags:
      ansible-collection: azure.infrastructure_config_demos
      ansible-role: vms
      ansible-task: create_rhel_vm
  register: vnic_results
  when: not create_public_ip

- name: Create public IP address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: "{{ public_ip_name }}"
    tags:
      ansible-collection: azure.infrastructure_config_demos
      ansible-role: vms
      ansible-task: create_rhel_vm
  register: ip_addr_results
  when: create_public_ip

- name: Create virtual network interface card with external ip
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ subnet_name }}"
    public_ip_name: "{{ public_ip_name }}"
    security_group: "{{ network_sec_group_name }}"
    tags:
      ansible-collection: azure.infrastructure_config_demos
      ansible-role: vms
      ansible-task: create_rhel_vm
  register: vnic_results
  when: create_public_ip

- name: Create VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    managed_disk_type: "{{ disk_type }}"
    admin_username: "{{ admin_user }}"
    admin_password: "{{ admin_password }}"
    linux_config: "{{ linux_config | default(omit) }}"
    ssh_password_enabled: "{{ ssh_password_enabled | default(omit) }}"
    ssh_public_keys: "{{ ssh_public_keys | default(omit) }}"
    network_interfaces: "{{ nic_name }}"
    os_type: "{{ os_type }}"
    image:
      offer: "{{ create_vm_offer }}"
      publisher: "{{ create_vm_publisher }}"
      sku: "{{ create_vm_sku }}"
      version: "{{ create_vm_version }}"
    max_price: "{{ create_vm_max_price }}"
    priority: "{{ create_vm_priority }}"
    tags:
      ansible-collection: azure.infrastructure_config_demos
      ansible-role: vms
      ansible-task: create_vm
      blueprint: "{{ create_vm_blueprint | default(omit) }}"

- name: Dump Private IP for VM which will be created
  ansible.builtin.debug:
    msg: "Private IP Address: {{ vnic_results.state.ip_configuration.private_ip_address | default('') }} ---- Public IP Address: {{ ip_addr_results.state.ip_address | default('') }}"

- name: Set Stat for Ansible Controller
  ansible.builtin.set_stats:
    data:
      azure_vnic_public_ip: "{{ ip_addr_results.state.ip_address | default('') }}"
      azure_vnic_private_ip: "{{ vnic_results.state.ip_configuration.private_ip_address | default('') }}"
    per_host: false
