---
- name: Delete VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    state: absent

- name: Delete Security Group
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ network_sec_group_name }}"
    state: absent
  when: network_sec_group_name is defined

- name: Delete NIC
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    state: absent
  when: nic_name is defined

- name: Delete Public IP
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ public_ip_name }}"
    state: absent
  when: public_ip_name is defined
