---
- name: Start VM
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_secret }}"
    api_host: "{{ proxmox_api_host }}"
    vmid: "{{ proxmox_vm_id }}"
    state: started
  when: proxmox_vm_migration_restart_vm
