---
- name: Notify the user that this next step will take a long time
  ansible.builtin.debug:
    msg: The next step can take a very long time depending on the size of the VM image.

- name: Copy the Azure VM image from Proxmox to localhost
  ansible.builtin.fetch:
    src: "{{ proxmox_vm_migration_image_dest }}"
    dest: "{{ proxmox_vm_migration_local_image_path }}"
    flat: true
    validate_checksum: false
  register: proxmox_vm_migration_copy_vm_file_results
