---
- name: Create Network Security Group that allows SSH
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ migrate_local_vm_resource_group }}"
    name: linux-migration-sg
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    tags:
      deployment: ansible

- name: Create public IP address
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "{{ migrate_local_vm_resource_group }}"
    allocation_method: Static
    name: linux-migration-public-ip
    tags:
      deployment: ansible
  register: migrate_local_vm_public_ip

- name: Create virtual network interface card
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "{{ migrate_local_vm_resource_group }}"
    name: "{{ migrate_local_vm_name }}-nic"
    virtual_network:
      name: "{{ migrate_local_vm_vnet_name }}"
      resource_group: "{{ migrate_local_vm_vnet_resource_group }}"
    subnet: "{{ migrate_local_vm_subnet_name }}"
    security_group: linux-migration-sg
    ip_configurations:
      - name: ip-configuration
        primary: true
        public_ip_address_name: "{{ migrate_local_vm_public_ip.state.name }}"
        private_ip_allocation_method: Dynamic
    tags:
      deployment: ansible
  register: migrate_local_vm_vnic

- name: Create a VM
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ migrate_local_vm_resource_group }}"
    name: "{{ migrate_local_vm_name }}"
    vm_size: "{{ migrate_local_vm_size }}"
    storage_account: "{{ migrate_local_vm_storage_account }}"
    admin_username: "{{ migrate_local_vm_username }}"
    admin_password: "{{ migrate_local_vm_password }}"
    virtual_network_name: "{{ migrate_local_vm_vnet_name }}"
    network_interfaces: "{{ migrate_local_vm_vnic.state.id }}"
    image:
      name: "{{ migrate_local_vm_image_name }}"
      resource_group: "{{ migrate_local_vm_resource_group }}"
    tags:
      deployment: ansible
  register: migrate_local_vm
