---
- name: Create VNET
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - region is defined
          - resource_group is defined
          - route_table_name is defined
          - vnet_name is defined
          - vnet_cidr is defined
          - subnet_name is defined
          - subnet_cidr is defined
        fail_msg: "Required variables not set"

    - name: Create a VNET
      ansible.builtin.import_role:
        name: lab.azure_infrastructure_config_demos.vnet
      vars:
        vnet_operation: create
