---
- name: Create Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - region is defined
          - resource_group is defined
        fail_msg: "Required variables not set"

    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ region }}"
