---
- name: Deploy Azure Log Analytics
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - resource_group is defined
          - workspace_name is defined
        fail_msg: "Required variables not set"

    - name: Deploy log analytics workspace
      ansible.builtin.import_role:
        name: log_analytics
        tasks_from: create_workspace
