---
- name: Uninstall Log Analytics Agent on Linux
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Remove Log Analytics Agent
      ansible.builtin.import_role:
        name: lab.azure_infrastructure_config_demos.log_analytics
        tasks_from: uninstall_agent
